### ISSUE TITLE
Excluded directories feature

### ISSUE THREAD

**Issue by Sabicool** [licht1stein/obsidian.el#101]
I am not a programmer and don't know how to do pull requests. Here is an implementation of excluding some directories in obsidian using the f.el package:

```emacs-lisp
(defcustom obsidian-exclude-directories nil
  "List of directories to exclude from Obsidian file searches.
Each directory should be a full path relative to `obsidian-directory`."
  :type '(repeat directory)
  :group 'obsidian)

(defun obsidian-not-in-excluded-directories-p (&optional file)
  "Check if FILE is not in any of the excluded directories.
If FILE is not provided, use the current buffer's file name."
  (let ((target-file (or file (when (buffer-file-name) (buffer-file-name)))))
    (if (and target-file obsidian-exclude-directories)
        (not (seq-some (lambda (dir)
                         (f-descendant-of-p target-file dir))
                       obsidian-exclude-directories))
      t)))

(defun obsidian-reset-cache ()
  "Clear and reset obsidian cache.
Excludes files in directories specified by `obsidian-exclude-directories`."
  (setq obsidian-files-cache
        (->> (directory-files-recursively obsidian-directory "\.*$")
             (-filter #'obsidian-file-p)
             (-filter #'obsidian-not-in-excluded-directories-p)))
  (setq obsidian-cache-timestamp (float-time)))
```

I use it to exclude folders for markdown files which may not have syntax correct yaml front matter resulting in obsidian.el throwing errors such as the one mentioned in #99

**Comment by licht1stein** [comment]
Thanks! The error will be fixed in the version 2.0, I think.

**Comment by Sabicool** [comment]
Either way, @licht1stein, I believe it would be useful to have this feature of excluding directories. For example, excluding the excalidraw folder.

**Comment by licht1stein** [comment]
Well if you ask @jayemar nicely maybe he'll include it in version 2. He's doing all the work for it.

**Comment by jayemar** [comment]
I added this feature yesterday alone with test and a mention in the README, so it should be all ready to go for 2.0.

**Comment by Sabicool** [comment]
> I added this feature yesterday along with tests and a mention in the README, so it should be all ready to go for 2.0.

Ah okay I will close this issue. Thank you for developing this package
