### ISSUE TITLE
Please don't depend on Company

### ISSUE THREAD

**Issue by AkibAzmain** [licht1stein/obsidian.el#17]
Your package depends on Company.  But there are other completion UIs like Corfu, Auto Complete, and obviously the minibuffer.  Please don't depend on Company.  I don't think it is necessary to depend on Company just because you define a Company backend, because there is a package named Cape which can convert Company backend function to CAPF (Completion at point function), allowing other completion UIs to use the completion function.

Here is the patch:  (I tried to create a pull request, but failed to push to my fork)

```patch
From c22227a8d7946b966eb3161cfa2a7a78bf7db215 Mon Sep 17 00:00:00 2001
From: Akib Azmain Turja <akib@disroot.org>
Date: Tue, 9 Aug 2022 22:44:43 +0600
Subject: [PATCH] Don't depend on Company

---
 obsidian.el | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/obsidian.el b/obsidian.el
index 91b56ca..330a858 100644
--- a/obsidian.el
+++ b/obsidian.el
@@ -40,7 +40,7 @@
 (require 's)
 
 (require 'cl-lib)
-(require 'company)
+(require 'company nil t)
 
 (require 'org)
 (require 'markdown-mode)
@@ -234,7 +234,10 @@ Optional argument IGNORED this is ignored."
   (interactive (list 'interactive))
 
   (cl-case command
-    (interactive (company-begin-backend 'obsidian-tags-backend))
+    (interactive (if (and (featurep 'company)
+                          (fboundp 'company-begin-backend))
+                     (company-begin-backend 'obsidian-tags-backend)
+                   (error "Company not installed")))
     (prefix (when (and
 		   (-contains-p local-minor-modes 'obsidian-mode)
 		   (looking-back obsidian--tag-regex nil))
@@ -413,7 +416,8 @@ See `markdown-follow-link-at-point' and
 ;;;###autoload
 (define-globalized-minor-mode global-obsidian-mode obsidian-mode obsidian-enable-minor-mode)
 
-(add-to-list 'company-backends 'obsidian-tags-backend)
+(when (boundp 'company-backends)
+  (add-to-list 'company-backends 'obsidian-tags-backend))
 
 ;; (obsidian-comment
 ;;  (use-package obsidian
-- 
2.37.1

```

**Comment by licht1stein** [comment]
Thanks, this sounds very reasonable. I'll test it and will release a new version soon.

**Comment by licht1stein** [comment]
What do you mean "failed to push to fork"? Maybe I can help you? Having a PR would be nice :)

**Comment by licht1stein** [comment]
https://github.com/licht1stein/obsidian.el/pull/19

**Comment by licht1stein** [comment]
Fixed in https://github.com/licht1stein/obsidian.el/releases/tag/1.1.1

**Comment by AkibAzmain** [comment]
> What do you mean "failed to push to fork"? Maybe I can help you? Having a PR would be nice :)

I don't know why, but often I can't connect to GitHub over SSH, although the website works fine.

> Fixed in https://github.com/licht1stein/obsidian.el/releases/tag/1.1.1

Thanks!
