### ISSUE TITLE
Alias front matter support

### ISSUE THREAD

**Issue by netromdk** [licht1stein/obsidian.el#18]
First of all: awesome package!

I use alias front matters to [define aliases in my Obsidian notes](https://help.obsidian.md/How+to/Add+aliases+to+note).
For instance, my home "+Home.md" has the following at the top:
```yaml
---
aliases: [000, Home, Beginning]
---
```

It would be great if `obsidian-jump` would show `000`, `Home`, and `Beginning` in addition to `+Home` in the list.

Thanks!

**Comment by licht1stein** [comment]
Hi, thanks for using and Im glad you like it! This doesn't look too difficult to implement, I'll try adding it soon.

**Comment by netromdk** [comment]
Sounds great. Thanks!

**Comment by netromdk** [comment]
Note, btw, that both `alias:` and `aliases:` work. Even though they only mention `aliases:`.

**Comment by licht1stein** [comment]
Good to know, thanks! I started working on implementing it, should be done soon. It would be great if you could test it before rease.

**Comment by netromdk** [comment]
Great. Yeah, I'll gladly help test it. :)

**Comment by licht1stein** [comment]
Implemented in https://github.com/licht1stein/obsidian.el/releases/tag/1.1.2

Thanks!

**Comment by netromdk** [comment]
Thank you!

**Comment by agisga** [comment]
Thank you for adding aliases support!
Note that Obsidian also allows to specify aliases as:

```
---
title: something
aliases:
- 000
- Home
- Beginning
---
```

(https://help.obsidian.md/Advanced+topics/YAML+front+matter), instead of `aliases: [000, Home, Beginning]`. I've been using this notation with my notes, because I find it more readable.

That notation doesn't seem to be supported by obsidian.el currently?

**Comment by licht1stein** [comment]
It should be supported actually, as these are alternative syntaxes for a yaml list. I'll check tomorrow.

**Comment by agisga** [comment]
> It should be supported actually, as these are alternative syntaxes for a yaml list. I'll check tomorrow.

You are right. Sorry. I just tested it with a small directory of test notes.
There must by another reason why I'm getting an "Unable to parse YAML" error with my Obsidian notes (will investigate).

**Comment by licht1stein** [comment]
Thanks for letting me know!
