### ISSUE TITLE
how to find markdown-mode-2.6 (which seems required for installation of obsidian.el)?

### ISSUE THREAD

**Issue by rdhyee** [licht1stein/obsidian.el#28]
When I try to install the `obsidian` package, I get the following error:

```
Need package 'markdown-mode-2.6` but only 2.5 is available
```

I don't understand how to find markdown-mode-2.6 -- the latest stable version is 2.5 from what I can see (https://github.com/jrblevin/markdown-mode/releases -- https://web.archive.org/web/20221001162717/https://github.com/jrblevin/markdown-mode/releases)

What can I do to get `markdown-mode-2.6`?

**Comment by licht1stein** [comment]
Hi @rdhyee thanks for writing. I have changed the requirement to 2.5 in the latest version.

**Comment by rdhyee** [comment]
@licht1stein Thanks so much for responding to my issue so quickly and for changing the requirements. I've now installed your package and am looking forward to digging into using it.
