### ISSUE TITLE
add backlinks

### ISSUE THREAD

**Issue by mastro35** [licht1stein/obsidian.el#29]
obsidian.el has changed my life, it is a really great piece of software, thanks!
However, it would be even better if you could see which backlinks are referring a specific node.

**Comment by suliveevil** [comment]
I think it's better done in Obsidian, there are some awesome plugins for relations of notes.

https://github.com/SkepticMystic/graph-analysis

https://github.com/hadynz/obsidian-sidekick

https://github.com/shoedler/crossbow

https://github.com/jerrywcy/obsidian-path-finder

https://github.com/AlexW00/obsidian-note-linker

https://github.com/Vinzent03/find-unlinked-files

https://github.com/ivaneye/obsidian-files-cooker

**Comment by mastro35** [comment]
I get your point, however, I’d rather be able to navigate my notes inside Emacs without even Obsidian installed on my desktop. 

This project allows me to navigate them just in one direction but it would be great if one could navigate through them backward too.

For my use case, many of the features of Obsidian and other plugins (like the graph for example) are nice-to-have features, while the ability to know which note refers to the one you're currently reading is a -must-have.

**Comment by suliveevil** [comment]
Obsidian,el is not a replica of Obsidian, Org-roam + md-roam is that thing.

https://github.com/org-roam/org-roam

https://github.com/nobiot/md-roam

**Comment by mastro35** [comment]
This seems a little bit overkill to me, I just need the backlink functionality, not the entire roam facility... Tnx anyway

**Comment by licht1stein** [comment]
> Obsidian.el is not a replica of Obsidian, Org-roam + md-roam is the thing.
> 
> https://github.com/org-roam/org-roam
> 
> https://github.com/nobiot/md-roam

Neither I am trying it to be a replacement. You can read the idea in the readme.

**Comment by suliveevil** [comment]
> Neither I am trying it to be a replacement. You can read the idea in the readme.

I love obsidian.el at first sight because of the idea in the readme 🥰

**Comment by licht1stein** [comment]
@suliveevil thank you ❤️

**Comment by licht1stein** [comment]
@mastro35 adding it in 1.1.6 :)

**Comment by mastro35** [comment]
Wow! Thanks!

**Comment by licht1stein** [comment]
> Wow! Thanks!

You are very welcome

**Comment by mastro35** [comment]
Just one thing: I've tried this version on my obsidian vault and looking
for backlinks on a specific note that should have two backlinks it returns
only one backlink.
Trying to debug it, I think I found a small bug in the
obsidian--elgrep-get-context function.
In particular, if I'm not wrong, this should be the correct versions (look
at the nth argument):

(defun obsidian--elgrep-get-context (match)
  "Get :context out of MATCH produced by elgrep."
  (let* ((result (->> match
                      (nth 2)
                      -flatten))
         (context (plist-get result :context)))
    context))

Can you double check this?

thanks!
D.

Il giorno mar 18 ott 2022 alle ore 17:15 Mykhaylo Bilyanskyy <
***@***.***> ha scritto:

**Comment by licht1stein** [comment]
Can you send me the links themself? e.g. `[foo](bar.md)`

**Comment by mastro35** [comment]
Sure! 
This is my file structure: 

myvault
|----Notes
       |-------Fornitori
                   |-----------fornitori.md (this is an index that links all the files in this directory)
                   |-----------forn-aaa.md
                   |----------- ...
                   |-----------forn-zzz.md
       |-------Contratti
                   |-----------contratti.md (this is an index that links all the files in this directory)
                   |-----------cont-aaa.md (this files links also forn-aaa.md)
                   |----------- ...
                   |-----------cont-zzz.md
       
This is the current situation.
If I go on `forn-aaa.md` and try to check backlinks, I only get the Fornitori\fornitori.md page bu I would expect it to returns me also the `Contratti\cont-aaa.md`.

All the links are made like this (no wiki links):
[myname](Fornitori/forn-aaa.md)
