### ISSUE TITLE
Default directory for creating new files

### ISSUE THREAD

**Issue by LeoCenturion** [licht1stein/obsidian.el#42]
It's great that `obsidian-follow-link-at-point` creates a new file when it does not exists (like obsidian).  Now we're creating notes in the `obsidian-specify-path` directory, i would like to set a default directory for creating new notes:  in my case  it would be $OBSIDIAN_ROOT/Inbox.
Can this package be configured to achieve that behavior and if not is it something that can be added?  
Thank you!

**Comment by licht1stein** [comment]
Hi, yes its right in the readme. 

`(setq obsidian-inbox-directory "Inbox")`
