### ISSUE TITLE
Following a link that doesn't exist ignores `obsidian-inbox-directory`

### ISSUE THREAD

**Issue by alphashuro** [licht1stein/obsidian.el#43]
When following a link that doesn't exist, I would expect the new note to be created in `obsidian-inbox-directory`, but instead it's created in the root dir. `obsidian-capture` works correctly though.

**Comment by licht1stein** [comment]
Makes sense, I'll fix it when I have a chance.

**Comment by licht1stein** [comment]
After careful consideration it became clear that the current behavior is correct. 

Links should not respect inbox setting, as this would make them non-deterministic. Closing the issue.
