### ISSUE TITLE
Package uses f.el without declaring the dependency, I think

### ISSUE THREAD

**Issue by fiddlemath** [licht1stein/obsidian.el#87]
I haven't looked deeply into the code, but I just did a fresh install of obsidian.el from MELPA. Following a wikilink to an not-yet-existing file (one of the first things I tried) failed because it couldn't find `f-mkdir-full-path`, a function from f.el.

I did not have f.el installed; after installing it from MELPA things worked fine.

**Comment by jayemar** [comment]
`f` is the first thing required by `obsidian.el`. Interesting that it wasn't installed for you after a fresh install.

https://github.com/licht1stein/obsidian.el/blob/24ff6ef051ba1f1a1e80a2132fdada37e77eaad6/obsidian.el#L39

**Comment by jayemar** [comment]
Closing as require statement already present to include required library
